### ISSUE TITLE
Compacity of the representation

### ISSUE THREAD

**Issue by moissinac** [zazuko/rdf-sketch#6]
Interesting tool but..
With the following rdf
```
@prefix barb: <http://givingsense.eu/barbules/> .
@prefix bbonto: <http://givingsense.eu/barbules/onto/> .

<http://givingsense.eu/barbules/BOIS_DU_SEIGNEUR> <http://givingsense.eu/barbules/onto/atterrissage> <http://givingsense.eu/barbules/CHAUSSINAND> ;
	<http://givingsense.eu/barbules/onto/base> <http://givingsense.eu/barbules/ACCONS> .
```
i'm getting a representation where the values are developed, which take a lot of place for each value which is an IRI (potentially long)
I expect barb:ACCONS in place of <http://givingsense.eu/barbules/ACCONS>
and with the code
```
@prefix barb: <http://givingsense.eu/barbules/> .
@prefix bbonto: <http://givingsense.eu/barbules/onto/> .

<http://givingsense.eu/barbules/BOIS_DU_SEIGNEUR> bbonto:atterrissage barb:CHAUSSINAND ;
	bbonto:base barb:ACCONS .
```
it's the same

**Comment by ktk** [comment]
You mean you would expect this:

<img width="405" alt="Screen Shot 2022-03-30 at 17 08 28" src="https://user-images.githubusercontent.com/583021/160807433-871d2159-dc6c-4ff7-84c6-35bc867d6dd4.png">

And not the unprefixed IRIs.

That's what you get on https://sketch.zazuko.com/ for your example by the way.

If this is what you mean, that's related to the way parsing is done right now in the VS Code extension. We will change that once but that needs some additional work first.

**Comment by BenjaminHofstetter** [comment]
Prefixes are more 'aggressively' used in the latest version.
