### ISSUE TITLE
Copy a Property is not possible

### ISSUE THREAD

**Issue by BenjaminHofstetter** [zazuko/rdf-sketch#8]
It's not possible to use copy (copy / paste) on a Property in Graph View. 

Maybe more precise it's not possible to select the text of a predicate/property. There is a conflict with the drag functionality of boxes within the graph view. 

This issue applies to SPEX too. 

I see two possible solution here. 

1. Provide a way to copy the predicate with a click. 
2. Limit the drag of a box to a special area (drag handle)

... and some issues with them. 

- (1) I don't know if copy a predicate is enough. Maybe the intention is some thing else. Copy what is in the box or a few lines or what ever. 
- (1)The User has a visual representation of the Resource as a Box. If the user tries to copy something he is guided by what the user is seeing. A click which copies something is not very obvious what it's actually going on. 

- (2) to limit the drag are (use a handle) gives us the possibility to let the user select text and let the HTML/Browser decide what it's copied. This is what the user is used to. But not necessary what is convenient. (we still don't know what is the intention of the copy action)
- (2) the GraphView is a "generic" component and it's not clear if that handle is really possible or what we want. Currently the graph view is used in SPEX and Sketch (and Sketch VSCode)

**Comment by cristianvasquez** [comment]
I faced the same problem some time ago. 

One solution could be that each node can have 2 states that behave differently.

1. View mode that allows you to drag around, resize, etc.
2. Edit/selectable mode that allows interaction with the node and select the elements within.

This provides a better separation of events to be handled in each node area.

This is a small recording of me using tldraw.  (as example) 

![Peek 2023-02-27 12-20](https://user-images.githubusercontent.com/361916/221550806-ebd71fb5-1805-42a0-8f63-ce7326a5940e.gif)

**Comment by BenjaminHofstetter** [comment]
This can be done with catching the ouse event on the label and stop propagation.

**Comment by BenjaminHofstetter** [comment]
solved in next
